const token=()=>localStorage.getItem('together_token')||'';
const api=async(path,options={})=>{const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(options.headers||{})}});const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{d={message:raw}}if(!r.ok)throw Error(d.message||'Request failed');return d};
const css=`.couplePanel{grid-column:1/-1;background:linear-gradient(135deg,#17121d,#111119);border:1px solid #3d294d;border-radius:22px;padding:25px}.coupleHead{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.coupleHead h2{margin:0 0 5px}.coupleBadge{background:#2a1930;color:#f0cfff;border:1px solid #5b3a68;border-radius:999px;padding:7px 11px;font-size:12px}.coupleSearch{display:flex;gap:8px;margin-top:18px}.coupleSearch input{flex:1}.coupleSearch button,.coupleAction{background:#f5f1ff;color:#17131f;font-weight:750;padding:11px 14px;border-radius:10px}.coupleResults,.coupleRequests{display:grid;gap:8px;margin-top:14px}.coupleUser,.coupleRequest,.couplePartner{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px;background:#1b1b25;border:1px solid #302f3b;border-radius:12px}.coupleUser span,.coupleRequest span,.couplePartner span{display:grid;gap:3px}.coupleUser small,.coupleRequest small,.couplePartner small{color:#9d9ba8}.coupleBtns{display:flex;gap:7px;flex-wrap:wrap}.coupleAccept{background:#a783ff;color:#17131f}.coupleReject{background:#20202a;color:#fff}.coupleConnected{margin-top:15px;padding:18px;background:linear-gradient(135deg,#24162b,#1b1824);border:1px solid #624171;border-radius:16px;text-align:center}.coupleHeart{font-size:34px}.coupleConnected h3{margin:5px 0}.coupleConnected p{color:#aaa7b2;margin:5px 0 14px}.coupleDanger{background:#3a171b;color:#ffb5b5;padding:10px 14px;border-radius:10px}.coupleNotice{margin-top:12px;padding:10px 12px;background:#211c2c;border:1px solid #4d3d66;border-radius:10px;color:#ddd2ea}@media(max-width:750px){.couplePanel{grid-column:1}.coupleSearch{flex-direction:column}.coupleUser,.coupleRequest,.couplePartner{align-items:flex-start;flex-direction:column}}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
async function mount(){if(!localStorage.getItem('together_token'))return;const grid=document.querySelector('.grid');if(!grid||grid.querySelector('[data-couple-panel]'))return;const panel=document.createElement('section');panel.className='couplePanel';panel.dataset.couplePanel='true';panel.innerHTML=`<div class="coupleHead"><div><h2>❤️ Couple Mode</h2><p class="muted">One special connection. Your private space starts here.</p></div><span class="coupleBadge">Phase 4 · Connection</span></div><div class="coupleBody">Loading…</div>`;grid.appendChild(panel);const body=panel.querySelector('.coupleBody');
 const render=async()=>{try{const d=await api('/api/couple');if(d.relationship){const p=d.relationship.partner;body.innerHTML=`<div class="coupleConnected"><div class="coupleHeart">❤️</div><h3>You & ${esc(p?.name||'your partner')}</h3><p>Connected since ${new Date(d.relationship.since).toLocaleDateString()}</p><button class="coupleDanger" data-action="disconnect">End couple connection</button></div><div class="coupleNotice">Your couple connection is exclusive: both accounts are locked to this partner until the connection is ended.</div>`;return}
 body.innerHTML=`<div class="coupleSearch"><input id="coupleQuery" placeholder="Search someone by name or email…"/><button class="coupleAction" data-action="search">Find partner</button></div><div class="coupleResults" id="coupleResults"></div>${d.incoming?.length?`<div class="coupleRequests"><h3>💌 Couple requests</h3>${d.incoming.map(r=>`<div class="coupleRequest"><span><b>${esc(r.user?.name||'Someone')}</b><small>${esc(r.user?.email||'Wants to connect with you')}</small></span><div class="coupleBtns"><button class="coupleAction coupleAccept" data-accept="${r.id}">Accept ❤️</button><button class="coupleAction coupleReject" data-reject="${r.id}">Reject</button></div></div>`).join('')}</div>`:''}${d.outgoing?.length?`<div class="coupleRequests"><h3>⏳ Sent requests</h3>${d.outgoing.map(r=>`<div class="coupleRequest"><span><b>${esc(r.user?.name||'Someone')}</b><small>Waiting for their response</small></span><span class="coupleBadge">Pending</span></div>`).join('')}</div>`:''}`;
 panel.querySelector('[data-action="search"]')?.addEventListener('click',async()=>{const q=panel.querySelector('#coupleQuery').value.trim();if(!q)return;const results=panel.querySelector('#coupleResults');results.innerHTML='Searching…';try{const found=await api('/api/users/search?q='+encodeURIComponent(q));results.innerHTML=found.length?found.map(u=>`<div class="coupleUser"><span><b>${esc(u.name)}</b><small>${esc(u.email)}</small></span><button class="coupleAction" data-partner="${u.id}">❤️ Choose</button></div>`).join(''):'<p class="muted">No users found.</p>';panel.querySelectorAll('[data-partner]').forEach(b=>b.addEventListener('click',async()=>{try{const x=await api('/api/couple/request/'+b.dataset.partner,{method:'POST'});body.insertAdjacentHTML('afterbegin',`<div class="coupleNotice">${esc(x.message)}</div>`);await render()}catch(e){body.insertAdjacentHTML('afterbegin',`<div class="coupleNotice">${esc(e.message)}</div>`)}}))}catch(e){results.innerHTML=`<div class="coupleNotice">${esc(e.message)}</div>`}});
 panel.querySelectorAll('[data-accept]').forEach(b=>b.addEventListener('click',async()=>{try{const x=await api('/api/couple/request/'+b.dataset.accept+'/accept',{method:'POST'});await render();}catch(e){alert(e.message)}}));panel.querySelectorAll('[data-reject]').forEach(b=>b.addEventListener('click',async()=>{try{await api('/api/couple/request/'+b.dataset.reject+'/reject',{method:'POST'});await render()}catch(e){alert(e.message)}}));panel.querySelector('[data-action="disconnect"]')?.addEventListener('click',async()=>{if(!confirm('End this couple connection?'))return;try{await api('/api/couple',{method:'DELETE'});await render()}catch(e){alert(e.message)}})}catch(e){body.innerHTML=`<div class="coupleNotice">${esc(e.message)}</div>`}};
 await render();}
const observer=new MutationObserver(()=>mount());observer.observe(document.body,{childList:true,subtree:true});mount();
