import {io as socketIO} from 'socket.io-client';

const token=()=>localStorage.getItem('together_token')||'';
const api=async(path,options={})=>{const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(options.headers||{})}});const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{d={message:raw}}if(!r.ok)throw Error(d.message||'Request failed');return d};
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const style=document.createElement('style');style.textContent=`.cr{background:#0b0b10;border:1px solid #3a3345;border-radius:16px;padding:14px}.crTop{display:flex;justify-content:space-between;align-items:center;gap:10px}.crTop button,.crCtl button,.crChat button{border:0;border-radius:9px;padding:9px 12px;font-weight:700;cursor:pointer}.crBack{background:#292532;color:#fff}.crShare{background:#a783ff}.crVideos{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:10px}.crVideo{width:100%;aspect-ratio:16/10;object-fit:cover;background:#030305;border-radius:12px}.crCtl{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.crCtl button{background:#f3effb;color:#17131f}.crStatus{color:#a9a3b0;font-size:13px}.crChatBox{height:170px;overflow:auto;background:#16151d;border-radius:10px;margin-top:10px;padding:9px}.crMsg{padding:5px 0}.crMsg b{color:#d5baff}.crChat{display:flex;gap:7px;margin-top:7px}.crChat input{flex:1;background:#101017;color:#fff;border:1px solid #383542;border-radius:9px;padding:10px}.crChat button{background:#a783ff;color:#17131f}@media(max-width:750px){.crVideos{grid-template-columns:1fr}}`;document.head.appendChild(style);

let active=false,socket=null,stream=null,pc=null,relationshipId=null,partnerId=null,screenTrack=null,muted=false,cameraOff=false;
const getPanel=()=>document.querySelector('[data-couple-panel]');
const cleanup=()=>{screenTrack?.stop();screenTrack=null;stream?.getTracks().forEach(t=>t.stop());stream=null;pc?.close();pc=null;socket?.disconnect();socket=null;active=false;partnerId=null};
const myId=()=>{try{return JSON.parse(atob(token().split('.')[1])).id}catch{return null}};
const append=(m)=>{const b=document.querySelector('#crChatBox');if(!b)return;b.insertAdjacentHTML('beforeend',`<div class="crMsg"><b>${esc(m.userName)}:</b> ${esc(m.text)}</div>`);b.scrollTop=b.scrollHeight};
const sendChat=()=>{const input=document.querySelector('#crChatInput'),text=input?.value.trim();if(!text||!socket)return;socket.emit('couple:chat',{relationshipId,text});input.value=''};
const setupPeer=async target=>{if(!stream||!socket)return;partnerId=target;pc?.close();pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>{const v=document.querySelector('#crRemote');if(v){v.srcObject=e.streams[0];v.play().catch(()=>{})}};pc.onicecandidate=e=>{if(e.candidate)socket.emit('couple:signal',{relationshipId,target,data:{candidate:e.candidate}})};const offer=await pc.createOffer();await pc.setLocalDescription(offer);socket.emit('couple:signal',{relationshipId,target,data:{description:pc.localDescription}})};
const handleSignal=async(from,data)=>{if(!stream||!socket)return;if(!pc){pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});stream.getTracks().forEach(t=>pc.addTrack(t));pc.ontrack=e=>{const v=document.querySelector('#crRemote');if(v){v.srcObject=e.streams[0];v.play().catch(()=>{})}};pc.onicecandidate=e=>{if(e.candidate)socket.emit('couple:signal',{relationshipId,target:from,data:{candidate:e.candidate}})}}if(data.description){await pc.setRemoteDescription(data.description);if(data.description.type==='offer'){const answer=await pc.createAnswer();await pc.setLocalDescription(answer);socket.emit('couple:signal',{relationshipId,target:from,data:{description:pc.localDescription}})}}else if(data.candidate){try{await pc.addIceCandidate(data.candidate)}catch{}}};
const share=async()=>{if(!stream||!pc)return;try{const ds=await navigator.mediaDevices.getDisplayMedia({video:{width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:30}},audio:false});screenTrack=ds.getVideoTracks()[0];const sender=pc.getSenders().find(s=>s.track?.kind==='video');if(sender)await sender.replaceTrack(screenTrack);const v=document.querySelector('#crLocal');if(v)v.srcObject=new MediaStream([screenTrack,...stream.getAudioTracks()]);screenTrack.onended=async()=>{const cam=stream.getVideoTracks()[0];if(sender&&cam)await sender.replaceTrack(cam);if(v)v.srcObject=stream;screenTrack=null}}catch(e){if(e.name!=='NotAllowedError')alert(e.message)}};
const loadMessages=async()=>{try{const d=await api('/api/couple/messages');const b=document.querySelector('#crChatBox');if(b){b.innerHTML=d.messages.map(m=>`<div class="crMsg"><b>${esc(m.userName)}:</b> ${esc(m.text)}</div>`).join('');b.scrollTop=b.scrollHeight}}catch{}};
const openRoom=async()=>{if(active)return;active=true;const panel=getPanel();if(!panel)return;try{const d=await api('/api/couple');if(!d.relationship)throw Error('Connect with a partner first.');relationshipId=d.relationship.id;await api('/api/couple/room',{method:'POST'});panel.querySelector('.coupleBody').innerHTML=`<div class="cr"><div class="crTop"><div><b>🔒 Private Couple Room</b><div class="crStatus" id="crStatus">Connecting…</div></div><button class="crBack" id="crBack">← Back</button></div><div class="crVideos"><video id="crLocal" class="crVideo" autoplay muted playsinline></video><video id="crRemote" class="crVideo" autoplay playsinline></video></div><div class="crCtl"><button id="crMic">🎙️ Mic</button><button id="crCam">📷 Camera</button><button id="crShare" class="crShare">🖥️ Share screen</button></div><div class="crChatBox" id="crChatBox"></div><div class="crChat"><input id="crChatInput" placeholder="Message your partner…"/><button id="crSend">Send</button></div></div>`;document.querySelector('#crBack').onclick=()=>{cleanup();const home=panel.querySelector('.coupleTabs [data-tab="home"]');if(home)home.click()};document.querySelector('#crSend').onclick=sendChat;document.querySelector('#crChatInput').onkeydown=e=>{if(e.key==='Enter')sendChat()};document.querySelector('#crMic').onclick=()=>{muted=!muted;stream?.getAudioTracks().forEach(t=>t.enabled=!muted)};document.querySelector('#crCam').onclick=()=>{cameraOff=!cameraOff;stream?.getVideoTracks().forEach(t=>t.enabled=!cameraOff)};document.querySelector('#crShare').onclick=share;await loadMessages();try{stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});document.querySelector('#crLocal').srcObject=stream}catch(e){document.querySelector('#crStatus').textContent='Camera/mic unavailable — chat is still available.'}socket=socketIO('http://localhost:5002',{auth:{token:token()}});socket.on('connect',()=>{document.querySelector('#crStatus').textContent='Private room connected';socket.emit('couple:join')});socket.on('couple:joined',async d=>{for(const p of d.peers||[])if(p!==myId())await setupPeer(p)});socket.on('couple:peer-joined',async({userId})=>{if(stream)await setupPeer(userId)});socket.on('couple:signal',e=>handleSignal(e.from,e.data));socket.on('couple:chat',append);socket.on('disconnect',()=>{const s=document.querySelector('#crStatus');if(s)s.textContent='Connection lost — reconnecting…'});}catch(e){active=false;alert(e.message)}};
const observer=new MutationObserver(()=>{const panel=getPanel();if(!panel||panel.dataset.roomPatch==='1')return;panel.dataset.roomPatch='1';panel.addEventListener('click',e=>{const b=e.target.closest('[data-tab="room"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();openRoom()},true)});observer.observe(document.body,{childList:true,subtree:true});
