import React,{useEffect,useRef,useState}from'react';

const EMPTY=Array(9).fill('');
const formats=[3,5,7];
const formatLabel=n=>`Best of ${n}`;
const nameFor=(id,people,user)=>id===user?.id?'You':people?.find(p=>p.id===id)?.name||'Player';
function Celebration({name}){return <div className="celebration"><div className="confetti">🎉 ✨ 🏆 ✨ 🎉</div><strong>{name} wins!</strong><span>What a game!</span></div>}
function SeriesBar({format,setFormat,wins,players,people,user,matchWinner,onNext,onNew}){const entries=Object.entries(players||{});return <><div className="seriesBar"><div><small>Match format</small><b>{formatLabel(format)}</b></div><div className="seriesScore">{entries.map(([id,symbol])=><span key={id}>{nameFor(id,people,user)} <b>{wins?.[symbol]||0}</b></span>)}</div><div className="formatBtns">{formats.map(n=><button key={n} className={format===n?'active':''} onClick={()=>setFormat(n)}>{n}</button>)}</div></div>{matchWinner&&<div className="winnerActions"><button onClick={onNew}>New match</button></div>}</>}

function TicTacToe({socket,roomId,user,people}){
 const[game,setGame]=useState({board:EMPTY,turn:'X',winner:null,players:{},wins:{},format:3,matchWinner:null});
 useEffect(()=>{const h=d=>d.roomId===roomId&&setGame(d);socket.on('game:tictactoe',h);socket.emit('game:tictactoe:join',{roomId});return()=>socket.off('game:tictactoe',h)},[socket,roomId]);
 const play=i=>{if(game.winner||game.matchWinner||game.board[i]||game.players[user.id]!==game.turn)return;socket.emit('game:tictactoe:move',{roomId,index:i})};
 const winnerName=game.matchWinner?nameFor(Object.entries(game.players).find(([,v])=>v===game.matchWinner)?.[0],people,user):'';
 return <div className="gameBox"><SeriesBar format={game.format} setFormat={n=>socket.emit('game:tictactoe:format',{roomId,format:n})} wins={game.wins} players={game.players} people={people} user={user} matchWinner={game.matchWinner} onNext={()=>socket.emit('game:tictactoe:next',{roomId})} onNew={()=>socket.emit('game:tictactoe:newmatch',{roomId})}/><div className="gameTop"><b>Tic-Tac-Toe</b><span>{game.matchWinner?`${winnerName} wins the match`:game.winner?game.winner==='draw'?'Round draw!':`${nameFor(Object.entries(game.players).find(([,v])=>v===game.winner)?.[0],people,user)} wins the round!`:game.players[user.id]?`You are ${game.players[user.id]} · ${game.turn}'s turn`:'Waiting for player…'}</span></div><div className="ttt">{game.board.map((x,i)=><button key={i} onClick={()=>play(i)}>{x}</button>)}</div>{game.winner&&!game.matchWinner&&<button className="gameReset" onClick={()=>socket.emit('game:tictactoe:next',{roomId})}>Next round</button>}{game.matchWinner&&<Celebration name={winnerName}/>}</div>}

function ConnectFour({socket,roomId,user,people}){
 const[game,setGame]=useState({board:Array(42).fill(''),turn:'R',winner:null,players:{},wins:{},format:3,matchWinner:null});
 useEffect(()=>{const h=d=>d.roomId===roomId&&setGame(d);socket.on('game:connect4',h);socket.emit('game:connect4:join',{roomId});return()=>socket.off('game:connect4',h)},[socket,roomId]);
 const drop=col=>{if(game.winner||game.matchWinner||!game.players[user.id]||game.players[user.id]!==game.turn)return;socket.emit('game:connect4:move',{roomId,col})};
 const winnerId=Object.entries(game.players).find(([,v])=>v===game.matchWinner)?.[0];
 return <div className="gameBox"><SeriesBar format={game.format} setFormat={n=>socket.emit('game:connect4:format',{roomId,format:n})} wins={game.wins} players={game.players} people={people} user={user} matchWinner={game.matchWinner} onNext={()=>socket.emit('game:connect4:next',{roomId})} onNew={()=>socket.emit('game:connect4:newmatch',{roomId})}/><div className="gameTop"><b>Connect Four</b><span>{game.matchWinner?`${nameFor(winnerId,people,user)} wins the match`:game.winner?game.winner==='draw'?'Round draw!':`${nameFor(Object.entries(game.players).find(([,v])=>v===game.winner)?.[0],people,user)} wins the round!`:game.players[user.id]?`You are ${game.players[user.id]} · ${game.turn}'s turn`:'Waiting for player…'}</span></div><div className="c4">{game.board.map((x,i)=><button key={i} onClick={()=>drop(i%7)} className={x==='R'?'redDisc':x==='Y'?'yellowDisc':''}>{x}</button>)}</div>{game.winner&&!game.matchWinner&&<button className="gameReset" onClick={()=>socket.emit('game:connect4:next',{roomId})}>Next round</button>}{game.matchWinner&&<Celebration name={nameFor(winnerId,people,user)}/>}</div>}

function Trivia({socket,roomId,user,people}){
 const[g,setG]=useState({format:5,index:0,score:{},question:null,matchWinner:null});const[locked,setLocked]=useState(false);
 useEffect(()=>{const h=d=>{if(d.roomId!==roomId)return;setG(d);setLocked(!!d.answered?.[user.id])};socket.on('game:trivia',h);socket.emit('game:trivia:join',{roomId});return()=>socket.off('game:trivia',h)},[socket,roomId,user.id]);
 const answer=i=>{if(locked||g.matchWinner)return;setLocked(true);socket.emit('game:trivia:answer',{roomId,answer:i})};
 const sorted=Object.entries(g.score||{}).sort((a,b)=>b[1]-a[1]);const winnerName=g.matchWinner&&g.matchWinner!=='draw'?nameFor(g.matchWinner,people,user):'';
 return <div className="gameBox"><div className="seriesBar"><div><small>Trivia match</small><b>{g.format} questions</b></div><div className="formatBtns">{[3,5,7,10].map(n=><button key={n} className={g.format===n?'active':''} onClick={()=>socket.emit('game:trivia:format',{roomId,format:n})}>{n}</button>)}</div></div><div className="scoreboard">{sorted.map(([id,v])=><span key={id}>{nameFor(id,people,user)} <b>{v} pts</b></span>)}</div>{g.matchWinner?<Celebration name={winnerName||'It’s a draw'}/>:<><div className="gameTop"><b>Question {g.index+1} / {g.format}</b><span>+1 point for each correct answer</span></div><h3>{g.question?.q||'Loading question…'}</h3><div className="answers">{(g.question?.a||[]).map((a,i)=><button key={a} onClick={()=>answer(i)}>{a}</button>)}</div><button className="gameReset" onClick={()=>socket.emit('game:trivia:next',{roomId})}>Next question</button></>}</div>}

function Scribble({socket,roomId,user,people}){
 const canvas=useRef(),drawing=useRef(false),last=useRef(null);const[g,setG]=useState({drawer:null,round:1,scores:{},word:null,started:false});const[word,setWord]=useState('');const[guess,setGuess]=useState('');const[status,setStatus]=useState('');
 useEffect(()=>{const state=d=>{if(d.roomId===roomId)setG(d)};const draw=d=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');ctx.lineCap='round';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(d.points[0].x,d.points[0].y);ctx.lineTo(d.points[1].x,d.points[1].y);ctx.stroke()};const clear=()=>{const c=canvas.current;if(c)c.getContext('2d').clearRect(0,0,c.width,c.height)};const result=d=>{if(d.roomId===roomId){setStatus(`${d.winnerName} guessed it! The word was ${d.word}.`);setG(x=>({...x,scores:d.scores}))}};const wordHandler=d=>setWord(d.word||'');socket.on('game:scribble',state).on('game:scribble:draw',draw).on('game:scribble:clear',clear).on('game:scribble:result',result).on('game:scribble:word',wordHandler);socket.emit('game:scribble:join',{roomId});return()=>{socket.off('game:scribble',state).off('game:scribble:draw',draw).off('game:scribble:clear',clear).off('game:scribble:result',result).off('game:scribble:word',wordHandler)}},[socket,roomId]);
 const isDrawer=g.drawer===user.id;const pos=e=>{const r=canvas.current.getBoundingClientRect();return{x:(e.clientX-r.left)*(canvas.current.width/r.width),y:(e.clientY-r.top)*(canvas.current.height/r.height)}};const start=e=>{if(!isDrawer)return;drawing.current=true;last.current=pos(e)};const move=e=>{if(!drawing.current||!isDrawer)return;const p=pos(e),a=last.current,ctx=canvas.current.getContext('2d');ctx.lineCap='round';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(p.x,p.y);ctx.stroke();socket.emit('game:scribble:draw',{roomId,points:[a,p]});last.current=p};const end=()=>{drawing.current=false;last.current=null};const submit=()=>{if(guess.trim()){socket.emit('game:scribble:guess',{roomId,guess});setGuess('')}};
 return <div className="gameBox"><div className="gameTop"><b>Scribble</b><span>{isDrawer?`Your word: ${word||'Press Start round'}`:g.started?'Guess the drawing!':'Waiting for the drawer…'}</span></div><div className="scribbleScores">{Object.entries(g.scores||{}).map(([id,v])=><span key={id}>{nameFor(id,people,user)} <b>{v} pts</b></span>)}</div><canvas ref={canvas} className="scribbleCanvas" width="900" height="500" onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerLeave={end}/><div className="scribbleControls">{isDrawer&&<><button onClick={()=>socket.emit('game:scribble:start',{roomId})}>Start round</button><button onClick={()=>socket.emit('game:scribble:clear',{roomId})}>Clear</button></>}{!isDrawer&&<div className="guessForm"><input value={guess} onChange={e=>setGuess(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder="Guess the word…"/><button onClick={submit}>Guess</button></div>}</div>{status&&<div className="roundResult">🎯 {status}</div>}</div>}

function SpyGame({socket,roomId,user}){
 const[g,setG]=useState({players:[],started:false,round:0,role:null,clue:null,spy:null,votes:{},result:null});const[vote,setVote]=useState('');
 useEffect(()=>{const h=d=>d.roomId===roomId&&setG(d);socket.on('game:spy',h);socket.emit('game:spy:join',{roomId});return()=>socket.off('game:spy',h)},[socket,roomId]);
 const start=()=>{setVote('');socket.emit('game:spy:start',{roomId})};const submit=()=>{if(vote)socket.emit('game:spy:vote',{roomId,target:vote})};
 return <div className="gameBox spyBox"><div className="gameTop"><b>Find the Spy</b><span>{g.started?'Discuss, then vote.':'At least 3 players recommended.'}</span></div><div className={`spyRole ${g.role==='spy'?'spy':'citizen'}`}>{g.started?<><small>Your role</small><strong>{g.role==='spy'?'🕵️ YOU ARE THE SPY':'👤 CIVILIAN'}</strong><span>{g.role==='spy'?'Blend in and discover the secret location.':`Secret location: ${g.clue}`}</span></>:<span>Waiting to start…</span>}</div><div className="spyPlayers">{(g.players||[]).map(p=><span key={p.id}>👤 {p.name}</span>)}</div>{g.result&&<div className="roundResult">🕵️ {g.result}</div>}<div className="spyControls"><button onClick={start}>{g.started?'Start new round':'Start spy round'}</button>{g.started&&<div className="voteGrid">{g.players.filter(p=>p.id!==user.id).map(p=><button className={vote===p.id?'active':''} key={p.id} onClick={()=>setVote(p.id)}>{p.name}</button>)}<button onClick={submit}>Vote</button></div>}</div></div>}

function CustomQuestions({socket,roomId}){const[q,setQ]=useState(''),[saved,setSaved]=useState([]),[analysis,setAnalysis]=useState(null);const submit=()=>{if(q.trim()){socket.emit('question:add',{roomId,text:q.trim()});setQ('')}};useEffect(()=>{const h=d=>{if(d.roomId===roomId){setSaved(d.questions||[]);setAnalysis(d.analysis||null)}};socket.on('question:update',h);socket.emit('question:list',{roomId});return()=>socket.off('question:update',h)},[socket,roomId]);return <div className="gameBox"><div className="gameTop"><b>Question Lab</b><span>Shared room questions</span></div><div className="questionForm"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Write a question for everyone…"/><button onClick={submit}>Add</button></div>{analysis&&<div className="analysis"><b>AI-ready analysis</b><span>Category: {analysis.category} · Type: {analysis.type} · Similarity: {Math.round(analysis.similarity*100)}%</span></div>}<div className="questionList">{saved.map(x=><div key={x.id}><span>{x.text}</span><small>{x.category}</small></div>)}</div></div>}

export default function Games({socket,roomId,user,people}){const[game,setGame]=useState('ttt');const tabs=[['ttt','Tic-Tac-Toe'],['c4','Connect Four'],['trivia','Trivia Battle'],['scribble','Scribble'],['spy','Find the Spy'],['questions','Question Lab']];return <section className="games"><div className="gamesHeader"><div><h2>Game Lounge</h2><p className="muted">Play together, keep score and celebrate every win.</p></div><div className="gameTabs">{tabs.map(([id,label])=><button key={id} className={game===id?'active':''} onClick={()=>setGame(id)}>{label}</button>)}</div></div>{game==='ttt'&&<TicTacToe socket={socket} roomId={roomId} user={user} people={people}/>} {game==='c4'&&<ConnectFour socket={socket} roomId={roomId} user={user} people={people}/>} {game==='trivia'&&<Trivia socket={socket} roomId={roomId} user={user} people={people}/>} {game==='scribble'&&<Scribble socket={socket} roomId={roomId} user={user} people={people}/>} {game==='spy'&&<SpyGame socket={socket} roomId={roomId} user={user}/>} {game==='questions'&&<CustomQuestions socket={socket} roomId={roomId}/>}</section>}
