services:
  - type: web
    name: together-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: web
    name: together-couple
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run couple-server
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false

  - type: web
    name: together-ml
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.ml
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false

  - type: web
    name: together-client
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./client/dist