services:
  - type: web
    name: together-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: web
    name: together-couple
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run couple-server
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false

  - type: web
    name: together-ml
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.ml
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false

  - type: web
    name: together-client
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://together-api-kg8o.onrender.com/api
      - key: VITE_API_ORIGIN
        value: https://together-api-kg8o.onrender.com
      - key: VITE_COUPLE_URL
        value: https://together-couple.onrender.com
      - key: VITE_AI_URL
        value: https://together-ml.onrender.com
      - key: VITE_COUPLE_SOCKET_URL
        value: https://together-couple.onrender.com
