import express from 'express';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import jwt from 'jsonwebtoken';

const app=express();
const PORT=process.env.COUPLE_PORT||5002;
const SECRET=process.env.JWT_SECRET||'together-dev-secret';
const dataDir=path.resolve('data');
const usersFile=path.join(dataDir,'db.json');
const couplesFile=path.join(dataDir,'couples.json');
fs.mkdirSync(dataDir,{recursive:true});
const readUsers=()=>{try{return JSON.parse(fs.readFileSync(usersFile,'utf8')).users||[]}catch{return[]}};
let store=fs.existsSync(couplesFile)?JSON.parse(fs.readFileSync(couplesFile,'utf8')):{relationships:[],requests:[]};
store.relationships||=[];store.requests||=[];
const save=()=>fs.writeFileSync(couplesFile,JSON.stringify(store,null,2));
const id=()=>crypto.randomUUID();
const pub=u=>u?({id:u.id,name:u.name,email:u.email,bio:u.bio||''}):null;
const auth=(req,res,next)=>{try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ','').trim(),SECRET);next()}catch{res.status(401).json({message:'Authentication required'})}};
const users=()=>readUsers();
const pairHasUser=r=>r.userA===r.userB;
const relationshipFor=uid=>store.relationships.find(r=>r.userA===uid||r.userB===uid)||null;
const requestBetween=(a,b)=>store.requests.find(r=>((r.from===a&&r.to===b)||(r.from===b&&r.to===a))&&r.status==='pending');
const statusFor=uid=>{const rel=relationshipFor(uid);const incoming=store.requests.filter(r=>r.to===uid&&r.status==='pending').map(r=>({...r,user:pub(users().find(u=>u.id===r.from))}));const outgoing=store.requests.filter(r=>r.from===uid&&r.status==='pending').map(r=>({...r,user:pub(users().find(u=>u.id===r.to))}));return{relationship:rel?{...rel,partner:pub(users().find(u=>u.id===(rel.userA===uid?rel.userB:rel.userA)))}:null,incoming,outgoing}};
app.use(express.json());
app.get('/api/couple',auth,(req,res)=>res.json(statusFor(req.user.id)));
app.post('/api/couple/request/:userId',auth,(req,res)=>{const me=req.user.id,other=req.params.userId;if(me===other)return res.status(400).json({message:'You cannot choose yourself as your partner.'});const all=users();if(!all.some(u=>u.id===other))return res.status(404).json({message:'User not found.'});if(relationshipFor(me))return res.status(409).json({message:'You already have a partner. Disconnect first before choosing another.'});if(relationshipFor(other))return res.status(409).json({message:'That person already has a partner.'});if(requestBetween(me,other))return res.status(409).json({message:'A couple request already exists between you.'});store.requests.push({id:id(),from:me,to:other,status:'pending',createdAt:new Date().toISOString()});save();res.status(201).json({message:'Couple request sent.',...statusFor(me)})});
app.post('/api/couple/request/:requestId/accept',auth,(req,res)=>{const me=req.user.id,rq=store.requests.find(r=>r.id===req.params.requestId&&r.to===me&&r.status==='pending');if(!rq)return res.status(404).json({message:'Couple request not found.'});if(relationshipFor(me)||relationshipFor(rq.from))return res.status(409).json({message:'One of you already has a partner.'});rq.status='accepted';store.requests=store.requests.filter(r=>r.id===rq.id||!(r.status==='pending'&&(r.from===me||r.to===me||r.from===rq.from||r.to===rq.from)));store.relationships.push({id:id(),userA:rq.from,userB:rq.to,since:new Date().toISOString(),createdAt:new Date().toISOString()});save();res.json({message:'❤️ You are now connected as partners.',...statusFor(me)})});
app.post('/api/couple/request/:requestId/reject',auth,(req,res)=>{const rq=store.requests.find(r=>r.id===req.params.requestId&&r.to===req.user.id&&r.status==='pending');if(!rq)return res.status(404).json({message:'Couple request not found.'});rq.status='rejected';save();res.json({message:'Request rejected.',...statusFor(req.user.id)})});
app.delete('/api/couple',auth,(req,res)=>{const uid=req.user.id;const rel=relationshipFor(uid);if(!rel)return res.status(404).json({message:'You are not currently connected to a partner.'});store.relationships=store.relationships.filter(r=>r.id!==rel.id);store.requests=store.requests.filter(r=>r.from!==uid&&r.to!==uid);save();res.json({message:'Couple connection ended.',...statusFor(uid)})});
app.listen(PORT,()=>console.log(`Together couple service: http://localhost:${PORT}`));
