import express from 'express';
import http from 'http';
import { Server } from 'socket.io';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';

const app=express();
const server=http.createServer(app);
const io=new Server(server,{cors:{origin:'*'}});
const PORT=process.env.PORT||5001;
const SECRET=process.env.JWT_SECRET||'together-dev-secret';
const dir=path.resolve('data');
const file=path.join(dir,'db.json');
fs.mkdirSync(dir,{recursive:true});
let db=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):{users:[],friends:[],rooms:[],messages:[],questions:[]};
db.users||=[];db.friends||=[];db.rooms||=[];db.messages||=[];db.questions||=[];
const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));
const id=()=>crypto.randomUUID();
const roomCode=()=>crypto.randomBytes(5).toString('hex').toUpperCase();
const uniqueRoomCode=()=>{let code;do code=roomCode();while(db.rooms.some(r=>r.code===code));return code};
let changed=false;for(const room of db.rooms)if(!room.code){room.code=uniqueRoomCode();changed=true}if(changed)save();
const pub=u=>({id:u.id,name:u.name,email:u.email,bio:u.bio||''});
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,DELETE,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});